### ISSUE TITLE
Need parens?

### ISSUE THREAD

**Issue by brentosaurus** [norswap/rocketcrash#5]
In the .h file, should there be parentheses around the bitwise AND on lines 109-110?

**Comment by norswap** [comment]
They're not needed because `&` has higher precedence than `&&` (\*) but you're right that it's bizarre to have them around the second `&` and not around the first. Feel free to make a pull request and I'll approve it 👍 

(\*) I use the mnemonic "posprema sore axodadotac" for pos-tfix pre-fix m-ultiplication a-ddition s-hift or-dering e-quality a-nd x-or o-r d-double a-nd d-ouble o-r t-ernacy a-ssignment c-omma.
